// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { DemoPalette, Page, Label } from "common.slint";
import { OrbiterWindow } from "demo.slint";


export component OrbiterPage inherits Page {
    header: "Orbiter Demo";
    in property <int> current-value;

    Window {
        width: 100%;
        height: 170px;
        y: 30px;

        OrbiterWindow {
            current-value <=> root.current-value;
        }
    }



}
